<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Lidarr.Plugin.Common.dll">
      <HintPath>lib/Lidarr.Plugin.Common.dll</HintPath>
    </Reference>

    <Reference Include="Lidarr.Plugin.Abstractions.dll">
      <HintPath>lib/Lidarr.Plugin.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
